/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      typography: () => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': 'var(--color-text-800)',
            '--tw-prose-headings': 'var(--color-text-900)',
            '--tw-prose-lead': 'var(--color-text-700)',
            '--tw-prose-links': 'var(--color-text-900)',
            '--tw-prose-bold': 'var(--color-text-900)',
            '--tw-prose-counters': 'var(--color-text-600)',
            '--tw-prose-bullets': 'var(--color-text-400)',
            '--tw-prose-hr': 'var(--color-text-300)',
            '--tw-prose-quotes': 'var(--color-text-900)',
            '--tw-prose-quote-borders': 'var(--color-text-300)',
            '--tw-prose-captions': 'var(--color-text-700)',
            '--tw-prose-code': 'var(--color-text-900)',
            '--tw-prose-pre-code': 'var(--color-text-100)',
            '--tw-prose-pre-bg': 'var(--color-text-900)',
            '--tw-prose-th-borders': 'var(--color-text-300)',
            '--tw-prose-td-borders': 'var(--color-text-200)',
            '--tw-prose-invert-body': 'var(--color-text-200)',
            '--tw-prose-invert-headings': 'white',
            '--tw-prose-invert-lead': 'var(--color-text-300)',
            '--tw-prose-invert-links': 'white',
            '--tw-prose-invert-bold': 'white',
            '--tw-prose-invert-counters': 'var(--color-text-400)',
            '--tw-prose-invert-bullets': 'var(--color-text-600)',
            '--tw-prose-invert-hr': 'var(--color-text-700)',
            '--tw-prose-invert-quotes': 'var(--color-text-100)',
            '--tw-prose-invert-quote-borders': 'var(--color-text-700)',
            '--tw-prose-invert-captions': 'var(--color-text-400)',
            '--tw-prose-invert-code': 'white',
            '--tw-prose-invert-pre-code': 'var(--color-text-300)',
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': 'var(--color-text-600)',
            '--tw-prose-invert-td-borders': 'var(--color-text-700)',
          },
        },
      }),
    },
  },
}
